version: '3.8'

services:
  api:
    build:
      context: backend
    container_name: backendEJ
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: npx prisma migrate deploy && npm start
    env_file:
      - ./.env
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: