version: '3.9'

services:
  api:
    build:
      context: backend
    container_name: backendEJ
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    command: npx prisma migrate deploy && npm start
    depends_on:
      - mysql
    env_file:
      - ./.env
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "${PORT_DB}:${PORT_DB}"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
